# Site settings
title: AragornSec
author: Manish
description: "Travel and Secure the world!"
show_excerpts: true
excerpt_separator: <!--more-->

# social links
twitter_username: sketchownlife
github_username: kr-manish
linkedin_username: manish-kumar-sec
instagram_username: sketchownlife

baseurl: /aragorn
theme: jekyll-theme-hacker

#show_downloads: true
# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title

plugins:
    - jekyll-seo-tag
