# Site settings
title: AragornSec
author: Manish Kumar
tagline: "Travel and Secure the world!"
description: "Blog to share my learnings on malware reversing/analysis and cybersecurity"
show_excerpts: true
excerpt_separator: <!--more-->

# social links
twitter_username: sketchownlife
github_username: kr-manish
linkedin_username: manish-kumar-sec
instagram_username: sketchingownlife
facebook_username: manish.kr8393

baseurl: /aragorn
theme: jekyll-theme-hacker

#Google-analytics
google_analytics: UA-122340797-1

#show_downloads: true
# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title

plugins:
    - jekyll-seo-tag

#comments
disqus:
    shortname: aragornsec
